name: mac v3.9

on:
  push:
    paths:
      - .github/workflows/build.yml
      - .github/workflows/build-python-39-macos.yml
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      python_version: 3.9
      os: macos-latest
