name: mac

on:
  push:
    paths:
      - src/**/*.py
      - tests/**/*.py
      - .github/workflows/build-for-os.yml
      - .github/workflows/build-macos.yml
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  build:
    uses: ./.github/workflows/build-for-os.yml
    with:
      os: macos-latest
