name: linux

on:
  push:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  build:
    uses: ./.github/workflows/build.yml@main
    with:
      os: ubuntu-latest
