name: python v3.11

on:
  push:
    paths:
      - .github/workflows/build.yml
      - .github/workflows/build-python-311-windows.yml
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      python_version: 3.11
      os: windows-latest
