name: Python 3.9

on:
  push:
    paths:
      - .github/workflows/build-for-os.yml
      - .github/workflows/build-python-37.yml
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  build:
    uses: .github/workflows/build-for-python-version.yml
    with:
      python_version: 3.9
