name: build-template

on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string
      python_version:
        required: true
        type: string

jobs:
  build:
    runs-on: ${{ inputs.os }}
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python_version }}
      - name: Install test requirements
        run: pip install -r requirements.txt
      - name: Install setuptools
        run: pip install setuptools
      - name: Install the package
        run: pip install -e .
      - name: Run Tests
        run: python -m pytest tests/ -v --cov --cov-report=xml --cov-report=term-missing
