name: mac

on:
  push:
    paths:
      - .github/workflows/build.yml
      - .github/workflows/build-macos.yml
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  build:
    uses: christianhelle/autofaker/.github/workflows/build.yml@main
    with:
      os: macos-latest
