name: windows

on:
  push:
    paths:
      - .github/workflows/build-for-os.yml
      - .github/workflows/build-windows.yml
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  build:
    uses: ./.github/workflows/build-for-os.yml
    with:
      os: windows-latest
