name: Pre-Integration

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  unit_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python_version:
          - "3.7"
          - "3.8"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        # this workflow needs java so that it can run a local instance of spark
        with:
          java-version: '8'
          distribution: 'temurin'
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python_version }}
      - name: Install test requirements
        run: pip install -r test_requirements.txt
      - name: Install the package
        run: python setup.py develop
      - name: Run Tests
        run: python -m pytest tests/
