name: sonar-cloud
on:
  push:
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-java@v2
        with:
          java-version: 8
          distribution: temurin

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.8

      - name: Install test requirements
        run: pip install -r requirements.txt

      - name: Install the package
        run: python setup.py develop

      - name: Run Tests
        run: python -m pytest tests/ -v --cov --cov-report=xml --cov-report=html

      - uses: actions/upload-artifact@v3
        with:
          name: code-coverage
          path: htmlcov

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
