name: test-template

on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string
      use-test-pypi:
        required: false
        type: boolean
        default: true

jobs:
  test:
    runs-on: ${{ inputs.os }}
    strategy:
      fail-fast: false
      matrix:
        python_version:
          - "3.7"
          - "3.8"
          - "3.9"
          - "3.10"
          - "3.11"
          - "3.12"
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python_version }}

      - name: Install Requirements
        run: |
          pip install pytest
          pip install faker
          pip install pandas
          pip install typing_inspect

      - name: Install Requirements from Test PyPi
        if: ${{ inputs.use-test-pypi }}
        run: pip install -i https://test.pypi.org/simple/ autofaker

      - name: Install Requirements from PyPi
        if: ${{ !inputs.use-test-pypi }}
        run: pip install autofaker

      - name: Run Tests
        run: python -m pytest tests/ -v
